version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynetwork

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - '3000:3000'
    depends_on:
      - postgres
    networks:
      - mynetwork

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '3001:3001'
    depends_on:
      - postgres
    networks:
      - mynetwork

  express-server:
    build:
      context: ./express-server
      dockerfile: Dockerfile
    ports:
      - '3002:3002'
    depends_on:
      - postgres
    networks:
      - mynetwork

volumes:
  pgdata:

networks:
  mynetwork:
